/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <sys/types.h>

ushort sqrtInt(uint x) 
{
    uint a = 0, b = 65535;
    uint m_prev = 0, m = (a / 2) + (b / 2);
    
    while (m != m_prev && a <= b && (m * m) != x) {
        if (m * m < x) {
            a = m;
        } else {
            b = m;
        }

        m_prev = m; m = (a / 2) + (b / 2);
    }

    return (ushort)m;
}

ushort isPrime(uint x) 
{
    for (uint i = 2; i <= sqrtInt(x); i++) if (!(x % i)) return 0;
    return (x < 2 ? 0 : 1);
}

int main(void)
{
    while (1) {
        ushort test_sqrt = sqrtInt(25);
        test_sqrt = sqrtInt(133);
        test_sqrt = isPrime(25);
        test_sqrt = isPrime(17);

    }

    return 0;
}
