/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "assignment1/assignment_1.h"
#include "stm32c0xx.h"
#include "stm_helper/my_stm_helper.h"

typedef enum {STATE_IDLE, STATE_ITEM_NEW, STATE_STAGE1_DONE, STATE_STAGE2_DONE, STATE_FAULT} SystemState_t;
volatile SystemState_t current_state = STATE_IDLE;

void init() {
    // 1. Enabling RCC
    Clock_Enable(GPIOA_BUS);
    Clock_Enable(GPIOB_BUS);

    // 2. Enable Input Pins - PA2, PA10, PB5
    GPIO_InitPinsSameMode(GPIOA, (uint8_t[]){2, 10}, INPUT, PULL_DOWN, 2);
    GPIO_InitPin(GPIOB, 5, INPUT, PULL_DOWN);

    // 3. Enable Output Pins - PA9 (Fault LED), PA0/PA1/PA4 (Real RGB), PA3/PA11/PA8 (Sensed RGB)
    GPIO_InitPinsSameMode(GPIOA, (uint8_t[]){9, 0, 1, 4, 3, 11, 8}, OUTPUT, PULL_DOWN, 7);

    // 3. Configure Timer

    // 4. Configure EXTI - PA2, PA10, PB5
    EXTI_Init(GPIOA, 2, TRIG_RISING);
    EXTI_Init(GPIOA, 10, TRIG_RISING);
    EXTI_Init(GPIOB, 5, TRIG_RISING);

    // 5. Enable NVIC
    NVIC_EnableIRQ(EXTI2_3_IRQn);
    NVIC_EnableIRQ(EXTI4_15_IRQn);  

    // 6. Enable System Tick
    SysTick_Init();
}

int main(void)
{
    init();
    /* Loop forever */
	while (1) {}
}
