/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdbool.h>
#include <stdint.h>
#include "assignment1/assignment_1.h"
#include "assignment1/my_helpers.h"
#include "stm32c0xx.h"
#include "stm_helper/my_stm_helper.h"

/* GENERATE NEW COLOR*/
volatile ItemColour_t truth_colour = OFF, sensor_colour = OFF;
volatile uint32_t lfsr_state = 0xA5A5A5A5;

void SysTick_Init(void){
    // Part of the Arm Cortex Peripherals. Not found in RM0490
    SysTick->LOAD = 0x00FFFFFF;
    SysTick->VAL  = 0;
    SysTick->CTRL = SysTick_CTRL_CLKSOURCE_Msk | SysTick_CTRL_ENABLE_Msk;
}

// Subroutine to add faulty detections
ItemColour_t Apply_LFSR_Fault(ItemColour_t true_col) {
    lfsr_state = (lfsr_state >> 1) ^ (-(lfsr_state & 1u) & 0xD0000001u);
    
    if ((lfsr_state % 100) < 20) {
        return (ItemColour_t)((true_col % 3) + 1);
    }
    return true_col;
}

// Subroutine to generate item and sensor detection 
void Generate_Next_Item(void) {
    lfsr_state ^= SysTick->VAL;
    truth_colour = (ItemColour_t)((lfsr_state % 3) + 1);
    sensor_colour = Apply_LFSR_Fault(truth_colour);
    Set_Truth_RGB(truth_colour);
    Set_Sensor_RGB(sensor_colour);
}

/* GENERATE NEW COLOR - END */

typedef enum {STATE_IDLE, STATE_ITEM_NEW, STATE_STAGE1, STATE_STAGE2, STATE_FAULT} SystemState_t;
volatile SystemState_t current_state = STATE_IDLE;
volatile bool isStateChange = false;

void init() {
    // 1. Enabling RCC
    Clock_Enable(GPIOA_BUS);
    Clock_Enable(GPIOB_BUS);

    // 2. Enable Input Pins - PA2, PA10, PB5
    GPIO_InitPinsSameMode(GPIOA, (uint8_t[]){2, 10}, INPUT, PULL_DOWN, 2);
    GPIO_InitPin(GPIOB, 5, INPUT, PULL_DOWN);

    // 3. Enable Output Pins - PA9 (Fault LED), PA0/PA1/PA4 (Real RGB), PA3/PA11/PA8 (Sensed RGB)
    GPIO_InitPinsSameMode(GPIOA, (uint8_t[]){9, 0, 1, 4, 3, 11, 8}, OUTPUT, PULL_DOWN, 7);

    // 4. Configure Timer

    // 5. Configure EXTI - PA2, PA10, PB5
    EXTI_Init(GPIOA, 2, TRIG_RISING);
    EXTI_Init(GPIOA, 10, TRIG_RISING);
    EXTI_Init(GPIOB, 5, TRIG_RISING);

    // 6. Enable NVIC
    NVIC_EnableIRQ(EXTI2_3_IRQn);
    NVIC_EnableIRQ(EXTI4_15_IRQn);

    // 7. Enable System Tick
    SysTick_Init();
}

void changeState(SystemState_t st) {
    current_state = st;
    isStateChange = true;
}

void EXTI2_3_IRQHandler() {
    if (current_state == STATE_IDLE && (EXTI->RPR1) & (1<<2)) {
        changeState(STATE_ITEM_NEW);
        EXTI->RPR1 |= (1 << 2); 
    }
}

void EXTI4_15_IRQHandler() {
    if ((EXTI->RPR1) & (1<<10)) {
        switch (current_state) {
            case STATE_ITEM_NEW:
                changeState(STATE_STAGE1);
                break;
            case STATE_STAGE1:
                changeState(STATE_STAGE2);
                break;
            case STATE_STAGE2:
                changeState(STATE_IDLE);
                break;
        }
        EXTI->RPR1 |= (1 << 10);
    }

    if ((EXTI->RPR1) & (1<<5)) {
        changeState(STATE_FAULT);
        EXTI->RPR1 |= (1 << 5); 
    }
}

int main(void)
{
    init();
    /* Loop forever */
	while (1) {
        if (!isStateChange) continue;
        isStateChange = false;

        switch (current_state) {
            case STATE_IDLE:
                Set_Truth_RGB(OFF);
                Set_Sensor_RGB(OFF);
                Set_Fault(PIN_LOW);
                break;

            case STATE_ITEM_NEW:
                Generate_Next_Item();
                Set_Fault(PIN_LOW);
                break;

            case STATE_STAGE1:
                Set_Fault(PIN_LOW);
                break;

            case STATE_STAGE2:
                Set_Fault(PIN_LOW);
                break;

            case STATE_FAULT:
                Set_Fault(PIN_HIGH);
                break;
        }
    }
}
